### ISSUE TITLE
"Guidance Needed: Fetching Files from External Resources (e.g., SharePoint) in Blazor WebAssembly"

### ISSUE THREAD

**Issue by RaveendraReshma** [mingyaulee/Blazor.BrowserExtension.Samples#9] opened 2024-12-02 16:26 UTC
**Context:**
I have developed a Chrome extension using Blazor WebAssembly (WASM) and have successfully established bidirectional communication between JavaScript and .NET Core functions. The extension incorporates business logic built with .NET Core 8 and runs entirely in the browser, with no server-side logic or API calls.

**Requirement:**
I need guidance or suggestions on how to fetch files from external resources, specifically SharePoint, to read their contents.

**Challenges:**
Many SharePoint-related NuGet packages, such as:
1. Microsoft.SharePoint.Client - is not compatible in .net core 8
2. PnP Core SDK - require a Client ID and Tenant ID, which are unavailable in this scenario due to certain reasons.
3. The extension is entirely runs client-side.

**Goal:**
To enable the extension to:
Connect to external resources (like SharePoint).
Fetch and read files securely without relying on Client ID and Tenant ID.

**Questions:**
Are there any recommended approaches or alternative libraries suitable for client-side Blazor WebAssembly that do not require Client ID and Tenant ID?
Is there a way to use organizational credentials or service accounts securely in this setup?

**Comment by mingyaulee** [comment] 2024-12-11 20:13
Closed as duplicate of https://github.com/mingyaulee/Blazor.BrowserExtension/issues/182

**Closed as completed by mingyaulee** 2024-12-11 20:13 UTC
